// GET /api/admin/labels/pdf — today's labels as one print-ready PDF.
//
// One 4×6in page per label, vector text, generated by the same engine the
// admin preview displays. `?disposition=inline` opens in the browser/print
// dialog; default is a download named dormers-labels-YYYY-MM-DD.pdf.
// `?order=DM-1042` narrows the batch to that single label (per-label view /
// reprint from the admin grid) — same engine, one page.
//
// Auth: middleware attaches x-user-* headers for /api/admin/*; we re-check
// the admin allowlist here so the route fails closed without middleware.

import { NextResponse } from 'next/server'
import { getUserFromHeaders } from '@/utils/supabase/auth'
import { isAdminEmail } from '@/contexts/admin/usecases/require-admin'
import { getDailyLabels, toLabelData } from '@/app/admin/labels/data'
import { renderLabelsPdf } from '@/app/admin/labels/label-pdf'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

export async function GET(request: Request) {
  const user = await getUserFromHeaders()
  if (!user || !isAdminEmail(user.email)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { dateIso, labels, noDeliveryReason } = await getDailyLabels()
  if (labels.length === 0) {
    return NextResponse.json({ error: noDeliveryReason ?? 'No labels today' }, { status: 404 })
  }

  const params = new URL(request.url).searchParams
  const order = params.get('order')
  const selected = order ? labels.filter(l => l.orderId === order) : labels
  if (selected.length === 0) {
    return NextResponse.json({ error: `No label ${order} today` }, { status: 404 })
  }

  const pdf = await renderLabelsPdf(await toLabelData(selected), {
    title: order ? `Dormers' Label — ${order}` : `Dormers' Labels — ${dateIso}`,
  })

  const inline = params.get('disposition') === 'inline'
  // order came from our own generated IDs (filter matched), so it's header-safe.
  const filename = order
    ? `dormers-label-${dateIso}-${order}.pdf`
    : `dormers-labels-${dateIso}.pdf`

  return new NextResponse(new Uint8Array(pdf), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `${inline ? 'inline' : 'attachment'}; filename="${filename}"`,
      'Cache-Control': 'no-store',
    },
  })
}
